<a href="https://colab.research.google.com/github/sera0911/asia_ai_study/blob/main/MachinLearning/ML_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ML day1 리뷰

인공지능 : 인간의 지능을 기계로 구현  
머신러닝 : 인공지능을 구현하는 구체적인 접근 방식으로 데이터로부터 스스로 학습을 통해 데이터를 가장 잘 표현하는 규칙, 패턴을 찾는 것(함수로 정의하는 과정)  
딥러닝 : 인간의 뇌 신경망을 모방한 인공 신경망 (입력층과 출력층 사이에 여러 층을 거쳐서 학습)  


지도학습 : 입력 데이터 (feature, 독립변수)와 출력데이터(class, target, label 종속변수)를 이용한 학습 - 분류, 회귀  
비지도 학습 : 입력 데이터를 이용한 학습 - 군집  
강화 학습 : 결과(정답)에 대한 보상이 주는 방식으로 학습  


머신러닝 라이브러리 - scikit-laern (샘플 데이터, 데이터 처리, 차원축소, 파라미터 튜닝, 평가. 머신러닝 알고리즘 클래스 등 제공)

load_xxxx() - keys(), data, target, target_names, feature_names   
make_xxxx()  
fetch_xxxx()   

Estimator - 데이터 학습fit()하고 예측predit()하는 알고리즘을 구현한 클래스들  
Transformer - 데이터 전처리(데이터를 수치 백터 변환) 클래스들 fit(), transform(), fit_transform()  

data wrangling:   
광범위한 의미의 원본 데이터를 정제(filter, 이상치 제거, 결측치 대체)하고 사용 가능한 형태로 구성하기 위한 변환 과정으로서 데이터 프레임을 가장 일반적인 데이터 구조로 활용  

concat()  
merge(base_df, join할 df, on=key 컬럼, how=조인방식)  
str -> datetime 변환 : to_datetime()   
datetime -> str 변환 : strtime()   
groupby().sum()  

데이터 정규화 (Scaling) - 데이커의 값이 너무 크거나 혹은 작은 경우에 모델 알고리즘 학습과정에서 0으로 수렴하거나 무한으로 발산할 수 있기 때문  
ex) MinMaxScaler, StandardScaler

데이터 전처리(데이터를 수치 백터 변환)을 수행할 데이타 유형  
범주형 (질적 변수) - 명목척도, 서열척도  
연속형 (양적 변수) - 서열척도, 비율척도  



### MD_day2 시작

#### 수치형 데이터 특성 스케일 변환
• 데이터에 이상치가 많다면 특성의 평균과 표준편차에 영향을 미치기 때문에 표준화에 부정적인 효과를 발생

• 이상치가 많은 경우 중간값과 사분위 범위를 사용하여 특성의 스케일을 조정

• RobustScaler - 모든 특성들이 같은 크기를 갖는다는 점에서 StandardScaler와 비슷하지만, 평균과 분산 대신
median과 quartile을 사용   
이상치에 영향을 받지 않는다.   
데이터에서 중간값을 빼고 IQR로 나눈다


In [3]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np

x= np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

scaler = preprocessing.RobustScaler()
robust_scaler = scaler.fit_transform(x)
print(robust_scaler)

[[-1.87387612]
 [-0.875     ]
 [ 0.        ]
 [ 0.125     ]
 [10.61488511]]


• QunatileTransformer - 훈련 데이터를 1,000개의 분위로 나누어 0~1 사이에 고르게 분포시킴으로써 이상치로 인한 영향을 줄여주는 특성 스케일 변환 클래스

In [4]:
import numpy as np
from sklearn import preprocessing

scaler2 = preprocessing.QuantileTransformer()
quantile_scaler = scaler2.fit_transform(x)
print(quantile_scaler)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2357: UserWarning: n_quantiles (1000) is greater than the total number of samples (5). n_quantiles is set to n_samples.
  % (self.n_quantiles, n_samples))


• Normalizer 클래스 - 정규화 변환 , 단위 길이의 합이 1이 되도록 개별 샘플의 값을 변환    
StandardScaler, RobustScaler, MinMaxScaler가 각 columns의 통계치를 이용한다면 Normalizer는 row마다 각각 정규화   
Normalizer는 유클리드 거리가 1이 되도록 데이터를 조정합니다.    
(유클리드 거리는 두 점 사이의 거리를 계산할 때 쓰는 방법, L2 Distance)    
행단위로 변환되므로 fit() 계산 작업 없이 transform() 사용

Norm은 벡터의 길이 혹은 크기를 측정하는 방법(함수) - 원점에서 벡터 좌표까지의 거리   

벡터 : 스칼라의 방향이 있는 것 (2차원 구조의 수치 데이터 EX)넘파이에서의 배열)  
스칼라 : 크기를 수치화 한 것  

L1은 절댓값을 사용 - Taxicab Norm, Manhattan norm(KNN, K평균 알고리즘에서 사용)       
L2은 피타고라스 정리를 사용한 거리 계산 Euclidean norm 

In [5]:
import numpy as np
from sklearn.preprocessing import Normalizer

features = np.array([[0.5, 0.5], [1.1, 3.4], [1.5, 20.2], [1.63, 34.4], [10.9, 3.3]])

#normalizer = Normalizer(nor=“l2")
#normalizer.transform(features)

fearues_l2_norm = Normalizer(norm="l2").transform(features)  #유클리드거리
print(fearues_l2_norm)
features_l1_norm = Normalizer(norm="l1").transform(features)
print(features_l1_norm)
print("첫 번째 샘플값의 합 : ", features_l1_norm[0, 0] + features_l1_norm[0, 1])

#검증하는 것
features / np.sum(np.abs(features), axis=1, keepdims=True)
features / np.sqrt(np.sum(np.square(features), axis=1, keepdims=True))

[[0.70710678 0.70710678]
 [0.30782029 0.95144452]
 [0.07405353 0.99725427]
 [0.04733062 0.99887928]
 [0.95709822 0.28976368]]
[[0.5        0.5       ]
 [0.24444444 0.75555556]
 [0.06912442 0.93087558]
 [0.04524008 0.95475992]
 [0.76760563 0.23239437]]
첫 번째 샘플값의 합 :  1.0


array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [6]:
#Normalizer의 norm 매개변수에 지정 옵션 max : 각 행의 최대값으로 행의 값을 나눔
import numpy as np
from sklearn.preprocessing import Normalizer

features = np.array([[0.5, 0.5], [1.1, 3.4], [1.5, 20.2], [1.63, 34.4], [10.9, 3.3]])
Normalizer(norm="max").transform(features)

array([[1.        , 1.        ],
       [0.32352941, 1.        ],
       [0.07425743, 1.        ],
       [0.04738372, 1.        ],
       [1.        , 0.30275229]])

#### 다항 특성과 교차항 특성 생성

2차원에 해당하는 비선형 관계일 때 PolynomialFeatures를 사용함  

• PolynomialFeatures 클래스 - 교차항을 포함, degree 매개변수가 다항식의 최대 차수를 결정  

예) degree=2는 2의 제곱까지 새로운 특성을 만듬    
degree=3은 2제곱과 3제곱까지 새로운 특성을 만듬  
interaction_only를 True로 지정하면 교차항 특성만 만들 수 있다.   

• 특성과 타깃 사이에 비선형 관계가 있다는 가정을 추가할 때 다항 특성을 듭니다.   

• 예) 주요 질병에 걸릴 확률에 나이가 미치는 영향은 일정한 상수값이 아니고 나이가 증가함에 따라 같이 증가한다는 의심을 할 수 있음

• 특성 x에 변동 효과를 주입하기 위해서 교차항 특성을 만들 수 있다.   
• include_bias 매개변수의 변수값은 True (변환된 특성에 상수항 1을 추가합니다.)

In [7]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

features = np.array([[2, 3], [2, 3], [2, 3]]) # 특성 행렬을 만듭니다

# PolynomialFeatures 객체를 만듭니다.
polynomial_interaction = PolynomialFeatures(degree=2, include_bias=False)
# 다항 특성을 만듭니다.
polynomial1 = polynomial_interaction.fit_transform(features) 
print(polynomial1)

#interaction_only= 교차항만 생성함 , degree=2 : 2의 제곱까지 차수 지정 
interaction = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
polynomial2 = interaction.fit_transform(features)
print(polynomial2)

#상수항 1을 추가: include_bias=True면 편향을 위한 변수(X0)인 1이 추가
polynomial_bias = PolynomialFeatures(degree=2, include_bias=True).fit(features)
polynomial3 = polynomial_bias.fit_transform(features)
print(polynomial_bias.get_feature_names())
print(polynomial3)

[[2. 3. 4. 6. 9.]
 [2. 3. 4. 6. 9.]
 [2. 3. 4. 6. 9.]]
[[2. 3. 6.]
 [2. 3. 6.]
 [2. 3. 6.]]
['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']
[[1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]
 [1. 2. 3. 4. 6. 9.]]


### 특성 변환 
 FunctionTransformer 를 사용하여 일련의 특성에 어떤 함수를 적용 할 수 있다  
하나 이상의 특성에 사용자 정의 변환을 적용  

 판다스의 apply()를 사용하여 동일한 변환을 수행할 수 있다

In [8]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

features = np.array([[2, 3], [2, 3], [2, 3]]) # 특성 행렬 데이터 생성

def add_ten(x): # 함수를 정의합니다.
  return x + 10

ten_transformer = FunctionTransformer(add_ten) # 변환기 객체 생성
ten_transformer.transform(features)# 특성 행렬을 변환

array([[12, 13],
       [12, 13],
       [12, 13]])

In [9]:
import pandas as pd

df = pd.DataFrame(features, columns=['feature_1', 'feature_2'])
df.apply(add_ten)

feature_1  feature_2
0         12         13
1         12         13
2         12         13

FunctionTransformer 클래스의 의 validate 매개변수가 True이면 입력값이 2차원 배열인지 확인하고 아닐 경우 예외를 발생시킴    
validate가 False이면 일차원 배열에도 적용할 수 있습니다.

ColumnTransformer : 특성 배열이나 데이터프레임의 열마다 다른 변환을 적용할 수 있다.

In [10]:
FunctionTransformer(add_ten, validate=False).transform(np.array([1, 2, 3]))

array([11, 12, 13])

In [11]:
from sklearn.compose import ColumnTransformer

def add_hundred(x): # 100을 더하는 함수 정의
  return x + 100

# (이름, 변환기, 열 리스트)로 구성된 튜플의 리스트를 ColumnTransformer에 전달합니다.
ct = ColumnTransformer(
[ ("add_ten", FunctionTransformer(add_ten, validate=True), ['feature_1']),
("add_hundred", FunctionTransformer(add_hundred, validate=True), ['feature_2'])])

ct.fit_transform(df)

array([[ 12, 103],
       [ 12, 103],
       [ 12, 103]])

### 이상치 검색
• 일반적인 방법은 데이터가 정규분포를 따른다는 가정을 기반으로 데이터를 둘러싼 타원을 그립니다.   타원 안의 샘플을 정상치(레이블 1)로 분류하고, 타원 밖의 샘플은 이상치(레이블 -1)로 분류  
• 이상치의 비율은 contamination 매개변수로 지정 (contamination은 데이터가 얼마나 깨끗한지 추측)  
• 데이터에 이상치가 적다면 contamination을 작게 지정, 데이터에 이상치가 많다면 contamination 값을 크게 설정 할 수 있다.

In [12]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

# 모의 데이터 생성, 뒤에  _변수는 반환값이 두개인데 두번째껀 쓰지 않아서 언더바로 표시
features, target = make_blobs(n_samples = 10, n_features = 2, centers = 1, random_state = 1)
print(features)

# 첫 번째 샘플을 극단적인 값으로 변경(이상치를 넣으려고)
features[0,0] = 10000 
features[0,1] = 10000
print(features)

outlier_detector = EllipticEnvelope(contamination=.1) # 이상치 감지 객체 생성
outlier_detector.fit(features) # 감지 객체를 훈련시킴
outlier_detector.predict(features) # 이상치를 예측

[[-1.83198811  3.52863145]
 [-2.76017908  5.55121358]
 [-1.61734616  4.98930508]
 [-0.52579046  3.3065986 ]
 [ 0.08525186  3.64528297]
 [-0.79415228  2.10495117]
 [-1.34052081  4.15711949]
 [-1.98197711  4.02243551]
 [-2.18773166  3.33352125]
 [-0.19745197  2.34634916]]
[[ 1.00000000e+04  1.00000000e+04]
 [-2.76017908e+00  5.55121358e+00]
 [-1.61734616e+00  4.98930508e+00]
 [-5.25790464e-01  3.30659860e+00]
 [ 8.52518583e-02  3.64528297e+00]
 [-7.94152277e-01  2.10495117e+00]
 [-1.34052081e+00  4.15711949e+00]
 [-1.98197711e+00  4.02243551e+00]
 [-2.18773166e+00  3.33352125e+00]
 [-1.97451969e-01  2.34634916e+00]]


array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

• 샘플을 전체적으로 보는 것보다 개별 특성에서 사분위범위(IQR)을 사용하여 극단적인 값을 구별할 수 있다.  
• IQR - 데이터에 있는 1사분위와 3사분위 사이의 거리  
• 이상치는 1사분위보다 1.5 IQR 이상 작은 값이나 3사분위보다 1.5 IQR 큰 값으로 정의한다

In [13]:
# 하나의 특성을 만든다.
feature = features[:,0]

# 이상치의 인덱스를 반환하는 함수를 만든다.
def indicies_of_outliers(x):
  q1, q3 = np.percentile(x, [25, 75])
  iqr = q3 - q1
  lower_bound = q1 - (iqr * 1.5)
  upper_bound = q3 + (iqr * 1.5)
  return np.where((x > upper_bound) | (x < lower_bound))

indicies_of_outliers(feature) # 함수 실행

(array([0]),)

In [14]:
#이상치 삭제
import pandas as pd

houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]
houses[houses['Bathrooms'] < 20] # 샘플을 필터링

Price  Bathrooms  Square_Feet
0  534433        2.0         1500
1  392333        3.5         2500
2  293222        2.0         1500

In [15]:
# 이상치로 표시하고 이를 특성의 하나로 포함
import numpy as np

houses["Outlier"] = np.where(houses["Bathrooms"] < 20, 0, 1) # 불리언 조건을 기반으로 특성을 생성
houses # 데이터 확인

Price  Bathrooms  Square_Feet  Outlier
0   534433        2.0         1500        0
1   392333        3.5         2500        0
2   293222        2.0         1500        0
3  4322032      116.0        48000        1

In [16]:
# 이상치 처리 - 이상치의 영향이 줄어줄 도록 특성을 변환

houses['Log_Of_Square_Feet'] = [np.log(x) for x in houses["Square_Feet"]] #로그 특성
houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956

#### 특성 이산화
• 수치 특성을 개별적인 구간으로 나누는 이산화는 수치 특성을 범주형처럼 다루어야 할 때 유용한 전략  
• Binarizer - 임계값에 따라 특성을 두 개의 구간으로 나눠줌  
• numpy.digitize() - 수치 특성을 세 개 이상의 여러 임계값에 따라 나누는 방법을 제공  
(bins 매개변수의 입력값은 각 구간의 왼쪽 경계값이다)

In [17]:
import numpy as np
from sklearn.preprocessing import Binarizer

age = np.array([[6], [12],[20],[36], [65]])
binarizer = Binarizer(18)
print(binarizer.fit_transform(age))

#bins 매개변수의 입력값은 각 구간의 왼쪽 경곗값입니다.
print(np.digitize(age, bins=[20, 30, 64]))

#right 매개변수를 True로 설정하면 이 동작을 바꿀 수 있습니다.
print(np.digitize(age, bins=[20, 30, 64], right=True))
print(np.digitize(age, bins=[18]))

[[0]
 [0]
 [1]
 [1]
 [1]]
[[0]
 [0]
 [1]
 [2]
 [3]]
[[0]
 [0]
 [0]
 [2]
 [3]]
[[0]
 [0]
 [1]
 [1]
 [1]]


• KBinsDiscretizer(v0.20) - 연속적인 특성값을 여러 구간으로 나눔  
encode 매개변수의 기본값은 'onehot'으로 원-핫 인코딩된 희소 행렬을 반환  
onehot-dense 매개변수 값은 원-핫 인코딩된 밀집 배열을 반환  
strategy 매개변수의 기본값은 'quantile'로 각 구간에 포함된 샘플 개수가 비슷하도록 만든다.  
strategy 매개변수의 기본값은 'uniform'은 구간의 폭이 동일하도록 만든다.  

• 연속된 값을 이산화하여 원-핫 인코딩으로 만들면 범주형 특성으로 다루기 편리합니다.   
• 구간은 bin_edges_속성에서 확인할 수 있다.

In [18]:
from sklearn.preprocessing import KBinsDiscretizer

age = np.array([[6], [12],[17], [20],[25], [26], [30], [32], [36], [40], [45], [65]])

kb = KBinsDiscretizer(4, encode='ordinal', strategy='quantile') # 네 개의 구간으로 나눕니다
print(kb.fit_transform(age))

kb = KBinsDiscretizer(4, encode='onehot-dense', strategy='quantile') # 원-핫 인코딩으로 반환
print(kb.fit_transform(age))

kb = KBinsDiscretizer(4, encode='onehot-dense', strategy='uniform') # 동일한 길이의 구간을 만듭니다
print(kb.fit_transform(age))
print(kb.bin_edges_)

[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[array([ 6.  , 20.75, 35.5 , 50.25, 65.  ])]


• 군집으로 샘플을 그룹으로 묶기  
• k개의 그룹이 있다는 것을 안다면 k-평균 군집(비지도 학습 알고리즘)을 사용하여 비슷한 샘플을 그룹으로 모을 수 있다.  
• 군집을 전처리 단계에서 사용할 수 있다.

In [19]:
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

# 모의 특성 행렬 생성
features, _ = make_blobs(n_samples = 50, n_features = 2, centers = 3, random_state = 1)
dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"])

clusterer = KMeans(3, random_state=0) # k-평균 군집 모델 생성
clusterer.fit(features) # 모델 훈련

dataframe["group"] = clusterer.predict(features) # 그룹 소속을 예측
dataframe.head(5) # 처음 5 개의 샘플을 조회

feature_1  feature_2  group
0  -9.877554  -3.336145      2
1  -7.287210  -8.353986      0
2  -6.943061  -7.023744      0
3  -7.440167  -8.791959      0
4  -6.641388  -8.075888      0

누락된 값을 가진 데이터 삭제   
• 머신러닝 알고리즘은 타깃과 특성 행렬에 있는 누락된 값을 다룰 수 없기 때문에 데이터에 있는 누락된 값을 무시 할 수 없고 전처리 과정에서 처리해주어야 합니다.   
• 넘파이를 이용하여 누락된 값이 있는 샘플을 삭제  


• 판다스를 사용하여 누락된 값이 있는 샘플을 삭제

In [20]:
import numpy as np
features = np.array([[1.1, 11.1],
[2.2, 22.2],
[3.3, 33.3],
[4.4, 44.4],
[np.nan, 55]]) # 특성 행렬을 생성
features[~np.isnan(features).any(axis=1)] # (~ 연산자를 사용하여) 누락된 값이 없는 샘플만 남김

dataframe = pd.DataFrame(features, columns=["feature_1", "feature_2"]) # 데이터 로드
dataframe.dropna() # 누락된 값이 있는 샘플을 제거

feature_1  feature_2
0        1.1       11.1
1        2.2       22.2
2        3.3       33.3
3        4.4       44.4

누락된 값 채우기  
• 데이터의 양이 작으면 k-최근접 이웃(KNN) 알고리즘을 사용해(가장 가까이 있는 k개의 샘플을 사용해) 누락된 값을 예측할 수 있다.  
• KNN - 누락된 값에 가장 가까운 샘플을 구하기 위해 누락된 값과 모든 샘플 사이의 거리를 계산하므로 작은 데이터셋에서는 수용할 만하지만 데이터넷의 샘플이 수백만 개라면 문제가 됨

In [21]:
import numpy as np
from fancyimpute import KNN
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_blobs

features, _ = make_blobs(n_samples = 1000, n_features = 2, random_state = 1) # 모의 특성 행렬 생성
scaler = StandardScaler() # 특성을 표준화
standardized_features = scaler.fit_transform(features)
true_value = standardized_features[0,0] # 첫 번째 샘플의 첫 번째 특성을 삭제
standardized_features[0,0] = np.nan

# 특성 행렬에 있는 누락된 값을 예측
features_knn_imputed = KNN(k=5, verbose=0).fit_transform(standardized_features)
print("실제 값:", true_value) # 실제 값과 대체된 값을 비교
print("대체된 값:", features_knn_imputed[0,0])

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)


실제 값: 0.8730186113995938
대체된 값: 1.0955332713113226


누락된 값 채우기  
• 사이킷런의 Imputer 모듈 - 특성의 평균, 중간값, 최빈값으로 누락된 값을 채울 수 있다.  
(KNN 보다는 결과가 좋지 않습니다)   
• 대용량 데이터셋에서는 누락된 값을 모두 평균값으로 채우는 것을 권장  
• SimpleImputer(v0.20) : strategy 매개변수 값 - mean, median, most_frequent, constant

In [22]:
from sklearn.impute import SimpleImputer

simple_imputer = SimpleImputer()
features_simple_imputed = simple_imputer.fit_transform(features)

print("실제 값 True Value:", true_value) # 실제 값과 대체된 값을 비교
print("대체된 값 Imputed Value:", features_simple_imputed[0,0])

실제 값 True Value: 0.8730186113995938
대체된 값 Imputed Value: -3.058372724614996


### 범주 데이터 처리

Label encoding  
• 문자열(범주형)값을 내림차순 정렬 후 0부터 1씩 증가하는 값으로 변환  
• 숫자의 차이가 모델에 영향을 주지 않는 트리 계열 모델(의사결정나무, 랜덤포레스트)에 적용한다  
• 숫자의 차이가 모델에 영향을 미치는 선형 계열 모델(로지스틱회귀, SVM, 신경망)에는 사용하지 않는다  
• sklearn.preprocessing.LabelEncoder  
• fit() – 어떻게 변환할 지 학습  
• transform() – 문자열을 숫자로 변환  
• fit_transform() – 학습과 변환을 한번에 처리  
• inverse_transform() – 숫자를 문자열로 변환  
• classes_ - 인코딩할 클래스 조회

In [23]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
items = ['TV', 'TV', '냉장고', '컴퓨터', '냉장고', '컴퓨터', '에어콘']
le = LabelEncoder()
le.fit(items)
label = le.transform(items)
print(label, type(label))
print(le.classes_)

[0 0 1 3 1 3 2] <class 'numpy.ndarray'>
['TV' '냉장고' '에어콘' '컴퓨터']


실습  adult data에 Label encoding 적용  
• 1994년 인구조사 데이터베이스에서 추출한 미국 성인의 소득 데이터셋   
• target은 income이며 수입이 $50,000 이하인지 초과인지로 분류   
• https://archive.ics.uci.edu/ml/datasets/adult  
• 범주형 : workclass, education,education-num,marital-status,occupation,relationship,race, gender, hours-perweek, native-country    
• 연속형 : age, fnlwgt, capital-gain, capital-loss

In [27]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier


cols= [ 'age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'gender' , 'capital-gain', 'capital-loss','hours-per-week', 'native-country', 'income']

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
df = pd.read_csv(url, header=None, names = cols, na_values='?')
print(df.head())
print(df.shape)


   age          workclass  fnlwgt  ... hours-per-week  native-country  income
0   39          State-gov   77516  ...             40   United-States   <=50K
1   50   Self-emp-not-inc   83311  ...             13   United-States   <=50K
2   38            Private  215646  ...             40   United-States   <=50K
3   53            Private  234721  ...             40   United-States   <=50K
4   28            Private  338409  ...             40            Cuba   <=50K

[5 rows x 15 columns]
(32561, 15)


In [28]:
df.shape
df = df.dropna() 

In [30]:
encoding_columns = [ 'workclass', 'education',  'marital-status', 'occupation', 'relationship', 'race', 'gender',  'native-country', 'income']
not_encoding_columns = [ 'age','fnlwgt', 'education-num',  'capital-gain', 'capital-loss',  'hours-per-week' ]

#각 컬럼별로 라벨 인코딩을 처리할 함수
#LabelEncoder는 1차원 배열(리스트, ndarray, Series) 단위로 처리한다
#인코딩전 원래 값들의 class들을 저장
#key:컬럼명, value:classes_
enc_classes = { }
def encoding_label(x) :   # x: 범주형 타입의 컬럼(Series)
    le = LabelEncoder()
    le.fit(x)
    label = le.transform(x)
    enc_classes[x.name] = le.classes_   #x.name 컬럼명
    return label

d1 = df[encoding_columns].apply(encoding_label)
d2 = df[not_encoding_columns]
data = d1.join(d2)
print(data.head())


   workclass  education  ...  capital-loss  hours-per-week
0          7          9  ...             0              40
1          6          9  ...             0              13
2          4         11  ...             0              40
3          4          1  ...             0              40
4          4          9  ...             0              40

[5 rows x 15 columns]


In [33]:
y = data['income']
X = data.drop(columns='income')

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
#분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=1)
#stratify는 classification을 다룰때 값을 target으로 지정해주면 각각의 비율(ratio)을 train/validation에 유지해 줍니다
#stratify 옵션을 지정해 주지 않고 classification 문제를 다룬다면, 성능의 차이가 많이 날 수 있습니다.
#모델 생성
tree = DecisionTreeClassifier(max_depth=9)
#학습
tree.fit(X_train, y_train)
#예측-검증
pred_train = tree.predict(X_train)
pred_test = tree.predict(X_test)
acc_train = accuracy_score(y_train, pred_train)
acc_test = accuracy_score(y_test, pred_test)

print(f'학습: {acc_train}, 테스트: {acc_test}')


학습: 0.8665321165321165, 테스트: 0.8503429214863343


One-Hot encoding  
• N개의 클래스를 N차원의 One-Hot 벡터로 표현되도록 변환  
• 고유값들을 피처로 만들고 정답에 해당하는 열은 1로 나머진 0으로 표시한다.  
• 숫자의 차이가 모델에 영향을 미치는 선형 계열 모델(로지스틱회귀, SVM, 신경망)에서 범주형 데이터 변환시 라
벨 인코딩 보다 원핫 인코딩을 사용한다  
• sklearn.preprocessing.OneHotEncoder

In [35]:
#판단스를 이용한 특성을 원-핫 인코딩 - pandas.get_dummies(DataFrame[, columns=[변환할 컬럼명]]) 함수

import numpy as np
import pandas as pd

items = np.array(['TV', '냉장고', '컴퓨터', '컴퓨터', '냉장고', '에어콘', '에어콘', '선풍기'])
pd.get_dummies(items)

TV  냉장고  선풍기  에어콘  컴퓨터
0   1    0    0    0    0
1   0    1    0    0    0
2   0    0    0    0    1
3   0    0    0    0    1
4   0    1    0    0    0
5   0    0    0    1    0
6   0    0    0    1    0
7   0    0    1    0    0

In [52]:
d ={ 'item' : items, 'cnt':np.arange(8) }
df = pd.DataFrame(d)
df.info()

items[..., np.newaxis]

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
ohe.fit(items[..., np.newaxis])
ohv = ohe.transform(items[..., np.newaxis])
print(ohv, type(ohv))
ohv.toarray()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   item    8 non-null      object
 1   cnt     8 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 256.0+ bytes
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 4)	1.0
  (4, 1)	1.0
  (5, 3)	1.0
  (6, 3)	1.0
  (7, 2)	1.0 <class 'scipy.sparse.csr.csr_matrix'>


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [51]:
ohe = OneHotEncoder(sparse=False)
ohe.fit(items[..., np.newaxis])
ohv = ohe.transform(items[..., np.newaxis])
ohv, type(ohv)
pd.DataFrame(ohv, columns=ohe.get_feature_names())

x0_TV  x0_냉장고  x0_선풍기  x0_에어콘  x0_컴퓨터
0    1.0     0.0     0.0     0.0     0.0
1    0.0     1.0     0.0     0.0     0.0
2    0.0     0.0     0.0     0.0     1.0
3    0.0     0.0     0.0     0.0     1.0
4    0.0     1.0     0.0     0.0     0.0
5    0.0     0.0     0.0     1.0     0.0
6    0.0     0.0     0.0     1.0     0.0
7    0.0     0.0     1.0     0.0     0.0

순서 없는 범주형 특성 인코딩  
• 사이킷런의 LabelBinarizer를 사용하여 문자열 타깃 데이터를 원-핫 인코딩  
• classes_ 속성에서 클래스를 확인

In [60]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

feature = np.array([["Texas"],
["California"],
["Texas"],
["Delaware"],
["Texas"]]) # 특성 데이터 생성

one_hot = LabelBinarizer() # 원-핫 인코더 생성
print(one_hot.fit_transform(feature)) # 특성을 원-핫 인코딩 변환
print(one_hot.classes_) #특성의 클래스를 확인
print(one_hot.inverse_transform(one_hot.transform(feature))) #원-핫 인코딩을 되돌립니다.

[[0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]]
['California' 'Delaware' 'Texas']
['Texas' 'California' 'Texas' 'Delaware' 'Texas']


문자열 타깃 데이터를 정수 레이블로 변환할 때는 LabelEncoder를 사용

In [58]:
multiclass_feature = [("Texas", "Florida"),
("California", "Alabama"),
("Texas", "Florida"),
("Delware", "Florida"),
("Texas", "Alabama")] # 다중 클래스 특성 생성

one_hot_multiclass = MultiLabelBinarizer() # 다중 클래스 원-핫 인코더 객체 생성
print(one_hot_multiclass.fit_transform(multiclass_feature)) # 다중 클래스 특성을 원-핫 인코딩 수행
print(one_hot_multiclass.classes_) #특성의 클래스를 확인

[[0 0 0 1 1]
 [1 1 0 0 0]
 [0 0 0 1 1]
 [0 0 1 1 0]
 [1 0 0 0 1]]
['Alabama' 'California' 'Delware' 'Florida' 'Texas']


• 사이킷런의 OneHotEncoder 클래스 - 정수형 특성을 원-핫 인코딩으로 변환  
v0.20부터는 문자열 데이터를 인식  
희소 배열을 반환이 기본값이며 sparse=False로 지정하면 밀집 배열을 반환  
• categories_속성으로 클래스를 확인할 수 있습니다.  
• 입력 특성 배열을 모두 범주형으로 인식하여 변환.  
• 특정 열에만 적용하려면 ColumnTransformer와 함께 사용

In [62]:
from sklearn.preprocessing import OneHotEncoder

feature = np.array([["Texas", 1],
["California", 1],
["Texas", 3],
["Delaware", 1],
["Texas", 1]]) # 여러 개의 열이 있는 특성 배열 생성

one_hot_encoder = OneHotEncoder(sparse=False)
print(one_hot_encoder.fit_transform(feature))
one_hot_encoder.categories_

[[0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0.]]


[array(['California', 'Delaware', 'Texas'], dtype='<U10'),
 array(['1', '3'], dtype='<U10')]

순서 있는 범주형 특성 인코딩  
• 순서가 있는 클래스는 순서 개념을 가진 수치값으로 변환해야 합니다.  
• 클래스 레이블 문자열을 정수로 매핑하는 딕셔너리를 만들고 이를 필요한 특성에 적용합니다

In [63]:
#판다스 데이터프레임의 replace()를 사용하여 문자열 레이블을 수치값으로 변환
import pandas as pd

dataframe = pd.DataFrame({"Score": ["Low", "Low", "Medium", "Medium", "High"]}) # 특성 데이터 생성
scale_mapper = {"Low":1,
"Medium":2,
"High":3} # 매핑 딕셔너리 생성
dataframe["Score"].replace(scale_mapper) # 특성을 정수로 변환

dataframe = pd.DataFrame({"Score": ["Low", "Low", "Medium", "Medium", "High", "Barely More Than Medium"]})
scale_mapper = {"Low":1,
"Medium":2,
"Barely More Than Medium": 3,
"High":4} # 매핑 딕셔너리 생성
dataframe["Score"].replace(scale_mapper) # 특성을 정수로 변환

0    1
1    1
2    2
3    2
4    4
5    3
Name: Score, dtype: int64

• 사이킷런 v0.20에서 범주형 데이터를 정수로 인코딩하는 OrdinalEncoder 추가  
• OrdinalEncoder는 클래스 범주를 순서대로 변환  
• 특정 열만 범주형으로 변환하려면 ColumnTransformer와 함께 사용

In [65]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

features = np.array(
[ [ "Low", 10],
["High", 50 ],
["Medium", 3] ] )

ordinal_encoder = OrdinalEncoder()
print(ordinal_encoder.fit_transform(features))
ordinal_encoder.categories_
#값이 하이, 로우, 미디엄순인건 10, 3, 50 에서 1, 3, 5순이기 때문

[[1. 0.]
 [0. 2.]
 [2. 1.]]


[array(['High', 'Low', 'Medium'], dtype='<U6'),
 array(['10', '3', '50'], dtype='<U6')]

특성 딕셔너리를 특성 행렬로 (변환) 인코딩   
• DictVectorizer클래스는 0이 아닌 값의 원소만 저장하는 희소 행렬을 반환  
• 자연어 처리 분야와 같은 매우 큰 행렬을 다룰 때 메모리 사용량을 최소화해야하기 때문에 유용  
• Sparse=False로 지정하면 밀집 벡터를 출력할 수 있습니다  
• get_feature_names( ) - 생성된 특성의 이름을 반환

In [67]:
from sklearn.feature_extraction import DictVectorizer
data_dict = [{"Red": 2, "Blue": 4},
{"Red": 4, "Blue": 3},
{"Red": 1, "Yellow": 2},
{"Red": 2, "Yellow": 2}] # 딕셔너리 생성

dictvectorizer = DictVectorizer(sparse=False) # DictVectorizer 객체 생성
features = dictvectorizer.fit_transform(data_dict) # 딕셔너리를 특성 행렬로 변환
print(features) # 특성 행렬을 확인

feature_names = dictvectorizer.get_feature_names() # 특성 이름을 얻습니다.
print(feature_names) # 특성 이름을 확인

import pandas as pd
pd.DataFrame(features, columns=feature_names)

[[4. 2. 0.]
 [3. 4. 0.]
 [0. 1. 2.]
 [0. 2. 2.]]
['Blue', 'Red', 'Yellow']


Blue  Red  Yellow
0   4.0  2.0     0.0
1   3.0  4.0     0.0
2   0.0  1.0     2.0
3   0.0  2.0     2.0

• 머신러닝 알고리즘은 행렬 형태의 데이터를 입력으로 사용  
• 예] 문서 데이터의 경우 각 문서에 등장한 모든 단어의 횟수를 담은 딕셔너리를 사이킷런의 DictVectorizer를 사
용하여 행렬 형태의 데이터로 생성

In [68]:
from sklearn.feature_extraction import DictVectorizer

# 네 개의 문서에 대한 단어 카운트 딕셔너리 데이터
doc_1_word_count = {"Red": 2, "Blue": 4}
doc_2_word_count = {"Red": 4, "Blue": 3}
doc_3_word_count = {"Red": 1, "Yellow": 2}
doc_4_word_count = {"Red": 2, "Yellow": 2}

doc_word_counts = [doc_1_word_count,
doc_2_word_count,
doc_3_word_count,
doc_4_word_count] # 리스트로 생성

dictvectorizer.fit_transform(doc_word_counts) # 단어 카운트 딕셔너리를 특성 행렬로 변환

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

누락된 클래스 값 대체 1   
• 머신러닝 분류 알고리즘을 훈련하여 누락된 값을 예측할 수 있다  
• (k-최근접 이웃KNN) 분류기를 사용, 이상적인 방법)

In [72]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

#X = 학습데이터
X = np.array([[0, 2.10, 1.45],
[1, 1.18, 1.33],
[0, 1.22, 1.27],
[1, -0.21, -1.19]]) # 범주형 특성을 가진 특성 행렬 데이터 생성

# 범주형 특성에 누락된 값이 있는 특성 행렬로 변환.
#X_with_nan = 테스트데이터
X_with_nan = np.array([[np.nan, 0.87, 1.31], [np.nan, -0.67, -0.22]])
clf = KNeighborsClassifier(3, weights='distance') # KNN 객체 생성
trained_model = clf.fit(X[:,1:], X[:,0]) #훈련
print(trained_model)

imputed_values = trained_model.predict(X_with_nan[:,1:]) # 누락된 값의 클래스를 예측
print(imputed_values)

# 예측된 클래스와 원본 특성을 열로 합칩니다.
X_with_imputed = np.hstack((imputed_values.reshape(-1,1), X_with_nan[:,1:]))
print(X_with_imputed)

np.vstack((X_with_imputed, X)) # 두 특성 행렬을 연결

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='distance')
[0. 1.]
[[ 0.    0.87  1.31]
 [ 1.   -0.67 -0.22]]


array([[ 0.  ,  0.87,  1.31],
       [ 1.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

누락된 클래스 값 대체 2  
• 누락된 값을 특성에서 가장 자주 등장하는 값으로 채우기

In [73]:
from sklearn.impute import SimpleImputer

# 두 개의 특성 행렬을 합칩니다.
X_complete = np.vstack((X_with_nan, X))

imputer = SimpleImputer(strategy='most_frequent')
imputer.fit_transform(X_complete)

array([[ 0.  ,  0.87,  1.31],
       [ 0.  , -0.67, -0.22],
       [ 0.  ,  2.1 ,  1.45],
       [ 1.  ,  1.18,  1.33],
       [ 0.  ,  1.22,  1.27],
       [ 1.  , -0.21, -1.19]])

불균형한 특성 클래스 처리   
• 타깃 벡터가 매우 불균형한 클래스로 이루어져 있는 경우 더 많은 데이터를 수집하는 것이 어렵다면 모델 평가 지표를 변경합니다.  
• 모델에 내장된 클래스 가중치 매개변수를 사용하거나 다운샘플링이나 업샘플링을 고려합니다.  
• RandomForestClassifier는 불균형한 영향을 줄일 수 있도록 클래스에 가중치를 부여할 수 있는 class_weight 매개 변수를 제공합니다.  
• class_weight값을 balanced로 지정하여 클래스 빈도에 반비례하게 자동으로 가중치를 만들 수 있습니다.

In [76]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

iris = load_iris() # 붓꽃 데이터 로드
features = iris.data # 특성 행렬
target = iris.target # 타깃 벡터
features = features[40:,:] # 처음 40개 샘플을 삭제
target = target[40:]   #target도 40개 삭제

target = np.where((target == 0), 0, 1) # 클래스 0을 음성 클래스로 하는 이진 타깃 벡터 생성
print(target) # 불균형한 타깃 벡터를 확인

weights = {0: .9, 1: 0.1} # 가중치 생성

RandomForestClassifier(class_weight=weights) # 가중치를 부여한 랜덤 포레스트 분류기 객체 생성

RandomForestClassifier(class_weight="balanced") # 균형잡힌 클래스 가중치로 랜덤 포레스트 모델을 훈련

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [77]:
# 각 클래스의 샘플 인덱스를 추출합니다.
i_class0 = np.where(target == 0)[0]
i_class1 = np.where(target == 1)[0]

# 각 클래스의 샘플 개수
n_class0 = len(i_class0)
n_class1 = len(i_class1)

# 클래스 0의 샘플만큼 클래스 1에서 중복을 허용하지 않고 랜덤하게 샘플을 뽑습니다.
# from class 1 without replacement
i_class1_downsampled = np.random.choice(i_class1, size=n_class0, replace=False)

# 클래스 0의 타깃 벡터와 다운샘플링된 클래스 1의 타깃 벡터를 합칩니다.
np.hstack((target[i_class0], target[i_class1_downsampled]))
# 클래스 0의 특성 행렬과 다운샘플링된 클래스 1의 특성 행렬을 합칩니다.
np.vstack((features[i_class0,:], features[i_class1_downsampled,:]))[0:5]

array([[5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4]])

In [78]:
# 클래스 1의 샘플 개수만큼 클래스 0에서 중복을 허용하여 랜덤하게 샘플을 선택합니다.
i_class0_upsampled = np.random.choice(i_class0, size=n_class1, replace=True)

# 클래스 0의 업샘플링된 타깃 벡터와 클래스 1의 타깃 벡터를 합칩니다.
np.concatenate((target[i_class0_upsampled], target[i_class1]))

# 클래스 0의 업샘플링된 특성 행렬과 클래스 1의 특성 행렬을 합칩니다.
np.vstack((features[i_class0_upsampled,:], features[i_class1,:]))[0:5]

array([[5.3, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3],
       [5. , 3.5, 1.6, 0.6],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6]])